"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

interface LegalDisclaimerProps {
  onAccept: () => void
  onBack: () => void
}

export function LegalDisclaimer({ onAccept, onBack }: LegalDisclaimerProps) {
  const [agreed, setAgreed] = useState(false)

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white">Review Legal Disclaimer</h1>
        <p className="text-slate-400">Please read and agree to continue with document generation.</p>
      </div>

      {/* Disclaimer box */}
      <Card className="bg-amber-500/10 border-amber-500/30 p-6">
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-amber-100">Important Legal Disclaimer</h3>
          <div className="text-sm text-amber-50/80 space-y-3">
            <p>
              This document is generated by AI for informational purposes only and{" "}
              <span className="font-semibold">does not constitute legal advice</span>. Laws vary significantly by
              country, state/province, and jurisdiction.
            </p>
            <p>
              You should <span className="font-semibold">consult a qualified legal professional</span> before using this
              document to ensure it complies with applicable laws and adequately protects your interests.
            </p>
            <p>
              We provide this tool as-is and make no guarantees about its accuracy, completeness, or suitability for
              your specific situation. You use this tool entirely at your own risk.
            </p>
            <p className="pt-2">
              <span className="font-semibold">Data Privacy:</span> Your information is processed securely and is never
              shared with third parties. We comply with GDPR and other international privacy standards.
            </p>
          </div>
        </div>
      </Card>

      {/* Acceptance checkbox */}
      <div className="flex items-start gap-3">
        <input
          type="checkbox"
          id="agree"
          checked={agreed}
          onChange={(e) => setAgreed(e.target.checked)}
          className="w-5 h-5 mt-1 rounded border-slate-600 bg-slate-700/50 text-blue-600 focus:ring-blue-500 cursor-pointer"
        />
        <label htmlFor="agree" className="flex-1 text-sm text-slate-300 cursor-pointer">
          I understand and agree that this document is for informational purposes only and that I will consult a legal
          professional if needed.
        </label>
      </div>

      {/* Trust badges */}
      <Card className="bg-slate-700/30 border-slate-600 p-4">
        <div className="grid grid-cols-3 gap-4 text-center text-xs">
          <div>
            <div className="text-lg mb-1">🔒</div>
            <p className="text-slate-300">Secure Processing</p>
          </div>
          <div>
            <div className="text-lg mb-1">🌍</div>
            <p className="text-slate-300">GDPR Compliant</p>
          </div>
          <div>
            <div className="text-lg mb-1">🔐</div>
            <p className="text-slate-300">Data Encrypted</p>
          </div>
        </div>
      </Card>

      {/* Action buttons */}
      <div className="flex justify-between pt-4">
        <Button
          onClick={onBack}
          variant="outline"
          className="px-6 py-2 border border-slate-600 text-slate-300 hover:bg-slate-700/50 bg-transparent"
        >
          Back
        </Button>
        <Button
          onClick={onAccept}
          disabled={!agreed}
          className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-2 rounded-lg font-semibold disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Generate Document
        </Button>
      </div>
    </div>
  )
}
